language: rust
rust: nightly

jobs:
  include:
    - stage: "Compile for amd64 Windows"
      os: windows
      
      script:
        - cargo build -Z unstable-options --verbose --release --bins --out-dir ./out

      deploy: &deploy_base
        provider: releases
        name: $TRAVIS_TAG
        api_key:
          secure: XoTb9Eeeypu/qBeE5EdrSjUoZSFePxr5gbTH0M0q/Do0GmnJGDLp5Vj4bcrmBLBtePHouyNlmvmQnCRt4ljRvatbxSUOF81qOrE+4um47UvxNoytPmNdaBnk/+SBV8rXNcdftuDXNmEhGXKVOtRWZQ7SGGgexlFpDk1V5k4XjIBKbXJHDHA75N+UrXv5EL/ZRsXEb4QTsYgRm83rOMafwxYMX/8s5Z8A/z/wcfPqtePTNBC7dZj505wDP5PHkm7NEvv9GG4jvxmw50KG79a3jOjofTA7f/bNQnZL4rsyoKwtHkBqw+MWNpaZ+1875eD4SC9WR5yrfVQwmc5H1reMywRy846TrY4d45O32zsQ6aSClhoWiBwsR7vG2qe3HQnN1zK6Spcoa8x6RSHsBIj3glwIzTtV+yBFBnX2VBi1rPxOBBwlmfxOqQmSgZc35pmZvNGqg6vh8HHyfOiohXMjafYOOrKfwuBLCuc2hr96hJ55rhldFk2lZgJ+fsqHc8mBJGkckhV0vlRBPkAfqZ6aykuMH+f3FQMK+VASmRQwNRSnra3YatBrX/l2r2Ofrqg3geABPzxXAGR5EEXjU2HPSZaByCS9jRdyncSwqoF2e8oYXNBAHTZceJZe0e6/fvQ2cNDkvaK0iunlQq7weUBXrOxLeCYW6e5e0XkPYwTGdXM=        
        on:
          all_branches: true
        draft: true
        overwrite: true
        skip_cleanup: true
        file_glob: true
        file: out/*
    
    - stage: "Compile for amd64 GNU/Linux and deploy GitHub Release"
      os: linux
      dist: jammy
      
      script:
        - cargo build -Z unstable-options --verbose --release --bins --out-dir ./out

      deploy:
        <<: *deploy_base
        draft: false
        file_glob: true
        file: out/*


before_deploy:
  - git config --local user.name "Eshark"
  - git config --local user.email "eshark@eshark.tech"
  - export TRAVIS_TAG="build-$TRAVIS_BUILD_NUMBER"
  - echo "Tagging commit ${TRAVIS_COMMIT} with tag ${TRAVIS_TAG}"
  - git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"
  - ls out/

cache: 
  - cargo