[workspace]
resolver = "2"

members = [
    "MainMenu",
    "InputHandlers",

    "Projects/Connect4",
    "Projects/EasterChallenges",

    "Units/Unit2-02-SelectionPractise",
    "Units/Unit2-03-DefensiveDesignA",
    "Units/Unit2-03-DefensiveDesignB",
]
